import turtle

def alapelem(hossz):
    t.right(90)
    t.fd(3.5*hossz)
    t.right(90)
    t.fd(2*hossz)
    t.right(90)
    t.fd(hossz)
    t.right(90)
    t.fd(2*hossz)
    t.left(90)
    t.fd(2.5*hossz)
    t.left(90)
    t.fd(hossz)
    t.left(90)
    t.fd(2*hossz)
    t.right(90)
    t.fd(hossz)
    t.left(90)
    t.fd(hossz/2)
    t.left(90)
    t.fd(hossz/2)
    t.right(90)
    t.fd(hossz)
    t.bk(hossz)
    t.left(90)
    t.fd(hossz/2)
    t.left(90)
    t.fd(hossz)
    t.right(90)
    t.fd(hossz)
    t.left(90)
    t.fd(1.5*hossz)
    t.right(90)

def sor(n,hossz):
    if n>0:
        for _ in range(n):
            alapelem(hossz)
            t.up()
            t.right(90)
            t.fd(1.5*hossz)
            t.left(90)
            t.fd(hossz)
            t.down()
        t.up()
        t.left(90)
        for _ in range(n):
            t.left(90)
            t.fd(hossz)
            t.right(90)
            t.fd(1.5*hossz)
        t.right(90)
        t.down()


ablak=turtle.Screen()
ablak.setup(500,500)
ablak.bgcolor('#FFFFFF')
ablak.title('Versenyfeladat')
t = turtle.Turtle()
t.up()
t.goto(-50,150)
t.down()

sor(3,50)

ablak.exitonclick()